1
00:00:01,220 --> 00:00:01,230
{"hi":"yes"}

2
00:00:13,220 --> 00:00:13,230
{"id":54,"type":"HOLOGRAM","name":"MONSTERS_DANCE","command":"Play"}

3
00:00:15,220 --> 00:00:15,230
{"wtf":"yes"}

4
00:02:00,220 --> 00:02:00,230
{"id":55,"type":"HOLOGRAM","name":"MONSTERS_SCAREY","command":"Play"}

5
00:04:00,220 --> 00:04:10,230
{"id":54,"type":"HOLOGRAM","name":"MONSTERS_DANCE","command":"Play"}

6
00:04:48,220 --> 00:04:48,230
{"id":37,"type":"HOLOGRAM","name":"WAITING","command":"Play"}