1
00:00:01,220 --> 00:00:01,230
{"hi":"yes"}

2
00:00:18,220 --> 00:00:23,230
{"id":66,"type":"HOLOGRAM","name":"WALL_BANGERS","command":"Play"}

3
00:00:54,220 --> 00:00:54,230
{"id":65,"type":"HOLOGRAM","name":"YOU_AXED","command":"Play"}

4
00:01:34,220 --> 00:01:34,230
{"id":65,"type":"HOLOGRAM","name":"YOU_AXED","command":"Play"}

5
00:02:00,220 --> 00:02:00,230
{"id":37,"type":"HOLOGRAM","name":"WAITING","command":"Play"}